name: Issue Labeler

on:
  issues:
    types:
      - opened

jobs:
  label-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Content
        id: check-issue-content
        run: |
          content=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)
          if [[ $content =~ "keyword1" ]]; then
            echo "::set-output name=labels::bug"
          elif [[ $content =~ "keyword2" ]]; then
            echo "::set-output name=labels::feature"
          else
            echo "::set-output name=labels::"
          fi

      - name: Add Labels
        if: steps.check-issue-content.outputs.labels != ''
        run: |
          labels=${{ steps.check-issue-content.outputs.labels }}
          IFS=',' read -ra labelArray <<< "$labels"
          for label in "${labelArray[@]}"; do
            echo "Adding label: $label"
            gh issue add-label ${{ github.event.issue.number }} "$label"
          done

      - name: Comment on Issue
        if: steps.check-issue-content.outputs.labels != ''
        run: |
          labels=${{ steps.check-issue-content.outputs.labels }}
          echo "Label(s) added: $labels"
          echo "Thank you for reporting the issue! We have labeled it accordingly."
          gh issue comment ${{ github.event.issue.number }} "Label(s) added: $labels\n\nThank you for reporting the issue! We have labeled it accordingly."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
